#######################################################
# This workflow gets triggered on a merge request
# to the main branch occurs.
#
# It performs the following tasks:
#    - checkout the repo
#    - log key details
#    - validate the packer template
#    - ???
#
#######################################################

name: Perform Packer Build
on: 
  push:
    branches:
      - develop

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Build
    
    # Variables for the build job
    env:
      dir-src: '${{ github.workspace }}/packer'

    # Build steps
    steps:
    
    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Log info
    - name: Log Info
      run: |
        echo Git Branch: ${{ github.ref }}
        echo Packer Directory ${{ env.dir-src }}: 
        ls -al ${{ env.dir-src }}
    
    # Validate the template
    - name: Validate templates
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: ${{ env.dir-src }}

      # Build the template
      - name: Build templates
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ${{ env.dir-src }}
          working_directory: infrastructure/packer
        env:
          PACKER_LOG: 1
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
